Feature http xa
dtm-labs/client-csharp pull request #69
Opened 2023-06-19 09:09 UTC by JackBOBO

1. add http xa pattern #68

2023-06-21 00:47 UTC, catcherwong requested changes

2023-06-21 00:47 UTC, catcherwong commented on src/Dtmcli/DtmClient.cs
> +            var queryParams = tb.TransType == "xa" ?
```suggestion
            var queryParams = tb.TransType == DtmCommon.Constant.TYPE_XA ?
```

2023-06-21 00:47 UTC, catcherwong commented on src/Dtmcli/Xa/XaLocalTransaction.cs
> +            xa.Gid = values[Request.GID];
```suggestion
values.TryGetValue(Request.GID, out var gid)
```

2023-06-21 00:47 UTC, catcherwong commented on src/Dtmcli/Xa/XaLocalTransaction.cs
> +        private Xa XaFromQuery(IDictionary<string, string> values)
What about adding a new method to read the values from `IQueryCollection` ?

```cs
 private Xa XaFromQuery(Microsoft.AspNetCore.Http.IQueryCollection query)
```

And **XaFromQuery** should be puiblic?

2023-06-21 00:47 UTC, catcherwong commented on src/Dtmcli/Xa/XaLocalTransaction.cs
> +            return xa;
Should check xa info here, valid or invalid.

2023-06-21 00:47 UTC, catcherwong commented on src/Dtmcli/Xa/XaLocalTransaction.cs
> +                conn.Open();
```suggestion
               await conn.OpenAsync();
```

2023-06-21 03:19 UTC, JackBOBO commented on src/Dtmcli/Xa/XaLocalTransaction.cs
> +        private Xa XaFromQuery(IDictionary<string, string> values)
OK, I'll move "XaFromQuery" to "Xa" as a public static function and add an overload of IQueryCollection.

2023-06-27 00:23 UTC, catcherwong approved these changes

2023-06-28 00:24 UTC, yedf2 commented
For mysql version less than 8.0, connection should be closed after `xa end`, or else `xa commit` in another connection will not succeed. It is a bug of mysql, and is fixed in mysql 8

2023-06-28 00:25 UTC, yedf2 requested changes

2023-06-28 00:25 UTC, yedf2 commented on src/Dtmcli/Xa/Xa.cs
> +        public static Xa FromQuery(IDtmClient dtmClient, Microsoft.AspNetCore.Http.IQueryCollection quersy)
`quersy` should be `query`

2023-06-28 07:14 UTC, JackBOBO commented
> For mysql version less than 8.0, connection should be closed after `xa end`, or else `xa commit` in another connection will not succeed. It is a bug of mysql, and is fixed in mysql 8

There is indeed this issue in versions below [MySQL 8](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-29.html#mysqld-8-0-29-xa), and even after closing the connection after `xa end` or `xa commit`, the problem still persists. However, when I add `pooling=false` to the connection string, it seems to work fine. I suspect that the MysqlConnector connection pool cannot support this scenario.

2023-06-29 00:49 UTC, yedf2 commented
So for XA transaction, you may disable pool.

In the document of dtm, the performance of XA transaction are not high, so disable pooling should be OK

2023-07-11 00:07 UTC, catcherwong commented
Can we merge this PR and release a new version now?

2023-07-11 00:20 UTC, JackBOBO commented
> Can we merge this PR and release a new version now?

Of course you can.

2023-07-11 00:32 UTC, merged